"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Menu } from "@/component/Menu";
import { MENU_PROPS } from "@/constants/menu";
import { Theme } from "@/constants/theme";
import React from "react";
import classNames from "classnames";
import styles from './styles.module.scss';
import { GlobalContext } from '../GlobalContext';
import { useTheme } from "@/hooks/useTheme";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// TODO: set this variable
const theme = Theme.default;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isOpen, setIsOpen] = React.useState<boolean>(false);
  const { theme, toggleTheme } = useTheme();


  return (
    <html lang="en">
      <body>
        <GlobalContext.Provider value={{ theme, toggleTheme }}>
          <main className={classNames(styles.app, styles[theme])}>
            <Menu
              {...MENU_PROPS}
              theme={theme}
              setIsOpen={setIsOpen}
              isOpen={isOpen}
            />
              <div className={classNames(styles.main, styles[theme], {[styles.isOpen]: isOpen})}>
                {children}
              </div>
          </main>
        </GlobalContext.Provider>
      </body>
    </html>
  );
}
